server {
    listen       80;
    server_name  localhost;

    # Webseiten-Verzeichnis
    root   /usr/share/nginx/html;
    index  index.html;

    # Zugriffs- und Fehler-Logs
    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}
